"""normalize application database schema

Revision ID: ee4c3478d994
Revises: 
Create Date: 2026-08-28 18:22:11.631565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4c3478d994'
down_revision: Union[str, Sequence[str], None] = '9f2c7a1b4d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'vehicle_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('alerts', 'alert_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('alerts', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_vehicle_id'), 'alerts', ['vehicle_id'], unique=False)
    op.alter_column('ev_data', 'event_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('ev_data', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('ev_data', 'schema_version',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('ev_data', 'producer',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('ev_data', 'vehicle_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('ev_data', 'battery',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('ev_data', 'temp',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('ev_data', 'speed',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('ev_data', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('ev_data', 'charging_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('ev_data', 'timestamp', existing_type=sa.TEXT(), type_=sa.DateTime(), nullable=False, postgresql_using='timestamp::timestamp without time zone')
    op.alter_column('ev_data', 'battery_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('ev_data', 'vehicle_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('ev_data', 'temperature_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index('idx_ev_data_vehicle_timestamp', 'ev_data', ['vehicle_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_ev_data_event_id'), 'ev_data', ['event_id'], unique=True)
    op.create_index(op.f('ix_ev_data_timestamp'), 'ev_data', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ev_data_vehicle_id'), 'ev_data', ['vehicle_id'], unique=False)
    op.create_unique_constraint('uq_ev_data_vehicle_timestamp', 'ev_data', ['vehicle_id', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ev_data_vehicle_timestamp', 'ev_data', type_='unique')
    op.drop_index(op.f('ix_ev_data_vehicle_id'), table_name='ev_data')
    op.drop_index(op.f('ix_ev_data_timestamp'), table_name='ev_data')
    op.drop_index(op.f('ix_ev_data_event_id'), table_name='ev_data')
    op.drop_index('idx_ev_data_vehicle_timestamp', table_name='ev_data')
    op.alter_column('ev_data', 'temperature_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ev_data', 'vehicle_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ev_data', 'battery_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ev_data', 'timestamp',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('ev_data', 'charging_status',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ev_data', 'location',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ev_data', 'speed',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('ev_data', 'temp',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('ev_data', 'battery',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('ev_data', 'vehicle_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('ev_data', 'producer',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ev_data', 'schema_version',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('ev_data', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('ev_data', 'event_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_alerts_vehicle_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.alter_column('alerts', 'status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('alerts', 'severity',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('alerts', 'alert_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('alerts', 'vehicle_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###

